#!/usr/bin/env python3
"""
Generate GRUB configuration from the full template.

When GRUB_MENU=minimal, only the selected desktop theme is shown as
the default (and only graphical) boot entry. When GRUB_MENU=all, the
full multi-theme menu is generated.
"""

import argparse
import os
import sys
import textwrap

DESKTOP_LABELS = {
    "classic":    "Classic Desktop (Win2000)",
    "luna":       "Luna Desktop (WinXP)",
    "aero":       "Aero Desktop (Win7)",
    "modern":     "Modern Desktop (Win8)",
    "fluent":     "Fluent Desktop (Win10)",
    "sunvalley":  "Sun Valley Desktop (Win11)",
    "none":       "Text Mode (CMD Shell)",
}

GRUB_PREAMBLE = """\
# ZirconOS v{version} GRUB Configuration
# Auto-generated by scripts/gen_grub_cfg.py
# Desktop: {desktop}  Menu mode: {menu_mode}

set timeout=5
set timeout_style=menu
set default=0

set menu_color_normal=light-gray/black
set menu_color_highlight=white/blue

set gfxmode=auto
insmod all_video
insmod gfxterm

if loadfont unicode ; then
    terminal_output gfxterm
elif loadfont ascii ; then
    terminal_output gfxterm
else
    terminal_output console
fi

set gfxpayload=keep

insmod multiboot2
insmod part_gpt
insmod part_msdos
insmod ext2
insmod fat
insmod chain
insmod ntfs

if [ "${{grub_platform}}" = "pc" ]; then
    insmod biosdisk
    insmod vbe
fi

if [ "${{grub_platform}}" = "efi" ]; then
    insmod efi_gop
    insmod efi_uga
fi
"""


def gen_entry(version, resolution, desktop, label=None):
    if label is None:
        label = DESKTOP_LABELS.get(desktop, desktop)
    if desktop == "none":
        return textwrap.dedent(f"""\
            menuentry "ZirconOS v{version} — {label}" {{
                multiboot2 /boot/kernel.elf -- console=serial,vga shell=cmd
                boot
            }}
        """)
    return textwrap.dedent(f"""\
        menuentry "ZirconOS v{version} — {label}" {{
            set gfxpayload={resolution}
            multiboot2 /boot/kernel.elf -- desktop={desktop}
            boot
        }}
    """)


def gen_common_entries(version):
    return textwrap.dedent(f"""\
        menuentry "ZirconOS v{version} — CMD Shell" {{
            multiboot2 /boot/kernel.elf -- console=serial,vga shell=cmd
            boot
        }}

        menuentry "ZirconOS v{version} — Normal Boot (Text)" {{
            multiboot2 /boot/kernel.elf
            boot
        }}

        menuentry "ZirconOS v{version} — Debug Mode (Serial + VGA)" {{
            multiboot2 /boot/kernel.elf -- console=serial,vga debug=1 verbose=1
            boot
        }}
    """)


def gen_zbm_submenu(version):
    return textwrap.dedent(f"""\
        submenu "ZirconOS Boot Manager (ZBM) >" {{

            if [ "${{grub_platform}}" = "efi" ]; then
                menuentry "ZBM — UEFI Boot Manager" {{
                    chainloader /EFI/BOOT/BOOTX64.EFI
                }}
            fi

            if [ "${{grub_platform}}" = "pc" ]; then
                menuentry "ZBM — BIOS Boot Manager (Chainload MBR)" {{
                    set root=(hd0)
                    chainloader +1
                }}
            fi

            menuentry "Back to Main Menu" {{
                configfile /boot/grub/grub.cfg
            }}
        }}
    """)


def gen_system_entries():
    return textwrap.dedent("""\
        menuentry "Reboot" {
            reboot
        }

        menuentry "Shutdown" {
            halt
        }
    """)


def gen_minimal(version, resolution, desktop):
    """Only the configured desktop as the default entry."""
    parts = [GRUB_PREAMBLE.format(version=version, desktop=desktop, menu_mode="minimal")]
    parts.append(gen_entry(version, resolution, desktop))
    parts.append(gen_common_entries(version))
    parts.append(gen_zbm_submenu(version))
    parts.append(gen_system_entries())
    return "\n".join(parts)


def gen_full(version, resolution, desktop):
    """All desktop themes in the menu, with configured desktop as default (index 0)."""
    all_desktops = ["classic", "luna", "aero", "modern", "fluent", "sunvalley"]

    parts = [GRUB_PREAMBLE.format(version=version, desktop=desktop, menu_mode="all")]

    # Default entry first
    if desktop != "none":
        label = DESKTOP_LABELS.get(desktop, desktop) + " [Default]"
        parts.append(gen_entry(version, resolution, desktop, label))

    # Remaining themes
    for dt in all_desktops:
        if dt != desktop:
            parts.append(gen_entry(version, resolution, dt))

    parts.append(gen_common_entries(version))
    parts.append(gen_zbm_submenu(version))
    parts.append(gen_system_entries())
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate GRUB configuration")
    parser.add_argument("--template", help="Full template (unused in script mode)")
    parser.add_argument("--output", required=True, help="Output grub.cfg path")
    parser.add_argument("--version", default="1.0.0")
    parser.add_argument("--resolution", default="1024x768x32")
    parser.add_argument("--desktop", default="sunvalley")
    parser.add_argument("--menu-mode", default="minimal", choices=["minimal", "all"])
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    if args.menu_mode == "minimal":
        cfg = gen_minimal(args.version, args.resolution, args.desktop)
    else:
        cfg = gen_full(args.version, args.resolution, args.desktop)

    with open(args.output, "w") as f:
        f.write(cfg)

    print(f"  GRUB config written: {args.output} (desktop={args.desktop}, mode={args.menu_mode})")


if __name__ == "__main__":
    main()
